add sub directory path to --sarif-category if it does not match $WORKSPACE
department-of-veterans-affairs/codeql-tools pull request #36
Opened 2023-07-11 16:28 UTC by arilivigni

Check if ${PWD} == ${WORKSPACE} if not then add relative PWD ro --sarif-category option

2023-07-12 20:04 UTC, arilivigni commented
@lindluni updates in the PR to include Windows support

2023-07-12 20:08 UTC, lindluni commented
Thank you @arilivigni, I will plug this into Jenkins and test it quick, but it looks good to me

2023-07-13 15:52 UTC, arilivigni commented
@lindluni is the Jenkins testing down as part of the checks not comprehensive? Is there a test I can run through on the Jenkins myself to verify so I can make and test changes better in the future?

2023-07-17 13:08 UTC, lindluni commented
It is comprehensive, but this scenario is not included since this requires configuration in the pipeline itself. Can you take a look at adding a second scenario to the vulnerable-node repos Jenkinsfile, it should be as simple as adding another  test but wrap it in the “dir” directive to change the working directory.

if you don’t get to it, I should have some time in a few hours.

2023-07-17 13:22 UTC, arilivigni commented
@lindluni I can totally do that and test it. Thanks for the direction to validate.

2023-07-22 14:57 UTC, arilivigni commented
@lindluni finally got this working and understand windows powershell paths more than I ever wanted to 🤣 
go in base vulnerable-go directory :: https://jenkins.github-apps.io/job/Go%20CodeQL%20-%20Windows/96/console
Javascript  vulnerable-go in public directory :: https://jenkins.github-apps.io/job/Go%20CodeQL%20-%20Windows/95/console

2023-07-24 19:42 UTC, arilivigni commented
@lindluni when you get chance can you review or give feedback on other changes needed. 🙇

2023-07-24 22:01 UTC, lindluni requested changes
Hey @arilivigni in general, this looks good, thank you for the effort. I noted we need to copy the Windows absolute path changes to Linux as well (even ones I may have missed, they all need to be copied).

And then there is something weird going on with the Windows library we need to investigate, I provided the API call to pull the generated categories for review in the comments, but the code scanning part of it works like a charm, just this minor quirk, which has to be corrected, as we need to know when users are scanning the whole repo, vs only scanning subdirectories for compliance reasons.

Thank you again for taking this on, lets figure out this last quirk and get this over the hump.

2023-07-24 22:02 UTC, lindluni commented
Also note I create two pipelines, one for Windows and one for Linux that runs both the regular and sub-directory scans in a single pipeline:

Windows: https://jenkins.github-apps.io/job/Go%20CodeQL%20-%20Windows/
Linux: https://jenkins.github-apps.io/job/Go%20CodeQL%20-%20Linux/

2023-07-25 13:32 UTC, arilivigni commented on jenkins/shared-libraries/windows/vars/ExecuteCodeQL.groovy
> +        Write-Output "Check if the current directory matches \$Env:WORKSPACE"
I will look into it. The output contains the right category so it is the reporting that is messing with the sarif category?

2023-07-25 13:45 UTC, arilivigni commented on jenkins/shared-libraries/windows/vars/ExecuteCodeQL.groovy
> +            tar -xf codeql.tgz --directory "\$pwd"
Done

2023-07-25 13:46 UTC, arilivigni commented on jenkins/shared-libraries/windows/vars/ExecuteCodeQL.groovy
> +        \$json_file = "\$Env:WORKSPACE\\.github\\emass.json"
Done

2023-07-25 14:00 UTC, arilivigni commented on jenkins/shared-libraries/windows/vars/ExecuteCodeQL.groovy
> +        Write-Output "Check if the current directory matches \$Env:WORKSPACE"
I just did the query on my recent run and it is correct. Did you change anything or how would this fix itself? I will do some more runs as well.

```
{
    "ref": "refs/heads/main",
    "commit_sha": "c0eb76ba613f5bde9156b671c4d0df380368a716",
    "analysis_key": "(default)",
    "environment": "{}",
    "category": "ois-javascript-public",
    "error": "",
    "created_at": "2023-07-25T13:48:38Z",
    "results_count": 19,
    "rules_count": 201,
    "id": 103559041,
    "url": "https://api.github.com/repos/department-of-veterans-affairs/vulnerable-go/code-scanning/analyses/103559041",
    "sarif_id": "f12d7ab4-2af1-11ee-8130-d18f054e1cef",
    "tool": {
      "name": "CodeQL",
      "guid": null,
      "version": "2.14.0"
    },
    "deletable": true,
    "warning": ""
  },
  {
    "ref": "refs/heads/main",
    "commit_sha": "c0eb76ba613f5bde9156b671c4d0df380368a716",
    "analysis_key": "(default)",
    "environment": "{}",
    "category": "ois-go",
    "error": "",
    "created_at": "2023-07-25T13:44:27Z",
    "results_count": 6,
    "rules_count": 51,
    "id": 103557645,
    "url": "https://api.github.com/repos/department-of-veterans-affairs/vulnerable-go/code-scanning/analyses/103557645",
    "sarif_id": "5de363e0-2af1-11ee-912f-63c714c67ec6",
    "tool": {
      "name": "CodeQL",
      "guid": null,
      "version": "2.14.0"
    },
    "deletable": true,
    "warning": ""
  },
```

2023-07-25 14:36 UTC, arilivigni commented on jenkins/shared-libraries/windows/vars/ExecuteCodeQL.groovy
> +        Write-Output "Check if the current directory matches \$Env:WORKSPACE"
I think this is happening on the linux side not the Windows side. I am troubleshooting that now

2023-07-25 15:09 UTC, arilivigni commented on jenkins/shared-libraries/windows/vars/ExecuteCodeQL.groovy
> +        Write-Output "Check if the current directory matches \$Env:WORKSPACE"
```
WORKSPACE: /home/jenkins/workspace/workspace/Go CodeQL - Linux
PWD: /usr/local/jenkins-service
Check if PWD matches WORKSPACE
The current directory and /home/jenkins/workspace/workspace/Go CodeQL - Linux do NOT match.
Sarif Category: ois-go-jenkins-service
```

```
WORKSPACE: /home/jenkins/workspace/workspace/Go CodeQL - Linux
PWD: /usr/local/jenkins-service
Check if PWD matches WORKSPACE
The current directory and /home/jenkins/workspace/workspace/Go CodeQL - Linux do NOT match.
Sarif Category: ois-javascript-jenkins-service
```

2023-07-25 16:21 UTC, arilivigni commented
@lindluni this is ready now with the linux changes applied along with the windows for the shared libraries 🚀

2023-07-26 08:24 UTC, lindluni approved these changes
Just a few comments on log statements to hopefully reduce confusion and limit support requests to understand what those log statements mean, but I am not going to hold up this PR. If you have cycles to a do a quick follow on PR to update the log statements that would be awesome, otherwise I will take care of it when I get back.

Note: I only commented on the log statements on the Linux library, the same statements should be copied to the Windows library.

Thank you @arilivigni for your work on this one and patience while we got it right!

2023-07-26 08:24 UTC, lindluni commented on jenkins/shared-libraries/linux/vars/ExecuteCodeQL.groovy
> +        echo "WORKSPACE: ${WORKSPACE}"
In a follow on PR can we update this to be natural language so users don’t send us requests trying to guess what these values mean:

```sh
echo “Current Jenkins Workspace: ${WORKSPACE}”
echo “Current working directory: ${PWD}”
echo “CodeQL database path: ${DATABASE_PATH}”
echo “CodeQL database bundle file name: ${DATABASE_BUNDLE}”
```

2023-07-26 08:24 UTC, lindluni commented on jenkins/shared-libraries/linux/vars/ExecuteCodeQL.groovy
> +        echo "Check if PWD matches WORKSPACE"
Can we make these natural language as well in the follow on PR, the last line should be `Check if current working directory and Jenkins workspace are the same directory`

2023-07-26 08:24 UTC, lindluni commented on jenkins/shared-libraries/linux/vars/ExecuteCodeQL.groovy
> +            echo "The current directory and ${WORKSPACE} match."
And this one should just be `The current working directory and Jenkins workspace match` (also with no period)

2023-07-26 08:24 UTC, lindluni commented on jenkins/shared-libraries/linux/vars/ExecuteCodeQL.groovy
> +            echo "The current directory and ${WORKSPACE} do NOT match."
This one should be `The current working directory and Jenkins workspace do not match, updating the SARIF category value to deduplicate Code Scanning results`

2023-07-26 08:24 UTC, lindluni commented on jenkins/shared-libraries/linux/vars/ExecuteCodeQL.groovy
> +        echo "Sarif Category: ois-${LANGUAGE}\${SEP}\${SUBDIR}"
```sh
echo “The SARIF category has been configured to `<value here>`”
```

2023-07-26 08:25 UTC, merged